/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 57ceecee541c26cec5f62a696ad8ea9f)
interface __BaseEnv_Env {
	SAVES: D1Database;
	ACCESS_DOMAIN: "https://krasne.cloudflareaccess.com";
	ACCESS_AUD: "8ba58012614e20ff0086f99441a2f058d3fe97ebf72199b128d3bc6065b56fe7";
}
declare namespace Cloudflare {
	interface PreviewEnv {
		SAVES: D1Database;
		ACCESS_DOMAIN: "https://krasne.cloudflareaccess.com";
		ACCESS_AUD: "8ba58012614e20ff0086f99441a2f058d3fe97ebf72199b128d3bc6065b56fe7";
	}
	interface ProductionEnv {
		SAVES: D1Database;
		ACCESS_DOMAIN: "https://krasne.cloudflareaccess.com";
		ACCESS_AUD: "8ba58012614e20ff0086f99441a2f058d3fe97ebf72199b128d3bc6065b56fe7";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_DOMAIN" | "ACCESS_AUD">> {}
}
