// AUTO-GENERATED FILE. Do not edit by hand.
// Source: src/words.ts
// Regenerate: node --experimental-strip-types scripts/generate-vocabulary-catalog.mjs
export const VOCABULARY = Object.freeze([
  Object.freeze({ id: "dog", category: "animals", shoppable: false, english: "dog", hebrew: "כלב" }),
  Object.freeze({ id: "cat", category: "animals", shoppable: false, english: "cat", hebrew: "חתול" }),
  Object.freeze({ id: "fish", category: "animals", shoppable: false, english: "fish", hebrew: "דג" }),
  Object.freeze({ id: "bird", category: "animals", shoppable: false, english: "bird", hebrew: "ציפור" }),
  Object.freeze({ id: "rabbit", category: "animals", shoppable: false, english: "rabbit", hebrew: "ארנב" }),
  Object.freeze({ id: "bear", category: "animals", shoppable: false, english: "bear", hebrew: "דוב" }),
  Object.freeze({ id: "fox", category: "animals", shoppable: false, english: "fox", hebrew: "שועל" }),
  Object.freeze({ id: "frog", category: "animals", shoppable: false, english: "frog", hebrew: "צפרדע" }),
  Object.freeze({ id: "panda", category: "animals", shoppable: false, english: "panda", hebrew: "פנדה" }),
  Object.freeze({ id: "monkey", category: "animals", shoppable: false, english: "monkey", hebrew: "קוף" }),
  Object.freeze({ id: "koala", category: "animals", shoppable: false, english: "koala", hebrew: "קואלה" }),
  Object.freeze({ id: "lion", category: "animals", shoppable: false, english: "lion", hebrew: "אריה" }),
  Object.freeze({ id: "tiger", category: "animals", shoppable: false, english: "tiger", hebrew: "נמר" }),
  Object.freeze({ id: "cow", category: "animals", shoppable: false, english: "cow", hebrew: "פרה" }),
  Object.freeze({ id: "pig", category: "animals", shoppable: false, english: "pig", hebrew: "חזיר" }),
  Object.freeze({ id: "horse", category: "animals", shoppable: false, english: "horse", hebrew: "סוס" }),
  Object.freeze({ id: "sheep", category: "animals", shoppable: false, english: "sheep", hebrew: "כבשה" }),
  Object.freeze({ id: "chicken", category: "animals", shoppable: false, english: "chicken", hebrew: "תרנגולת" }),
  Object.freeze({ id: "duck", category: "animals", shoppable: false, english: "duck", hebrew: "ברווז" }),
  Object.freeze({ id: "penguin", category: "animals", shoppable: false, english: "penguin", hebrew: "פינגווין" }),
  Object.freeze({ id: "elephant", category: "animals", shoppable: false, english: "elephant", hebrew: "פיל" }),
  Object.freeze({ id: "giraffe", category: "animals", shoppable: false, english: "giraffe", hebrew: "ג׳ירפה" }),
  Object.freeze({ id: "zebra", category: "animals", shoppable: false, english: "zebra", hebrew: "זברה" }),
  Object.freeze({ id: "turtle", category: "animals", shoppable: false, english: "turtle", hebrew: "צב" }),
  Object.freeze({ id: "whale", category: "animals", shoppable: false, english: "whale", hebrew: "לווייתן" }),
  Object.freeze({ id: "dolphin", category: "animals", shoppable: false, english: "dolphin", hebrew: "דולפין" }),
  Object.freeze({ id: "butterfly", category: "animals", shoppable: false, english: "butterfly", hebrew: "פרפר" }),
  Object.freeze({ id: "bee", category: "animals", shoppable: false, english: "bee", hebrew: "דבורה" }),
  Object.freeze({ id: "snail", category: "animals", shoppable: false, english: "snail", hebrew: "חילזון" }),
  Object.freeze({ id: "unicorn", category: "animals", shoppable: false, english: "unicorn", hebrew: "חד־קרן" }),
  Object.freeze({ id: "apple", category: "food", shoppable: true, english: "apple", hebrew: "תפוח" }),
  Object.freeze({ id: "banana", category: "food", shoppable: true, english: "banana", hebrew: "בננה" }),
  Object.freeze({ id: "orange", category: "food", shoppable: true, english: "orange", hebrew: "תפוז" }),
  Object.freeze({ id: "strawberry", category: "food", shoppable: true, english: "strawberry", hebrew: "תות" }),
  Object.freeze({ id: "grapes", category: "food", shoppable: true, english: "grapes", hebrew: "ענבים" }),
  Object.freeze({ id: "watermelon", category: "food", shoppable: true, english: "watermelon", hebrew: "אבטיח" }),
  Object.freeze({ id: "pear", category: "food", shoppable: true, english: "pear", hebrew: "אגס" }),
  Object.freeze({ id: "peach", category: "food", shoppable: true, english: "peach", hebrew: "אפרסק" }),
  Object.freeze({ id: "pineapple", category: "food", shoppable: true, english: "pineapple", hebrew: "אננס" }),
  Object.freeze({ id: "lemon", category: "food", shoppable: true, english: "lemon", hebrew: "לימון" }),
  Object.freeze({ id: "cherries", category: "food", shoppable: true, english: "cherries", hebrew: "דובדבנים" }),
  Object.freeze({ id: "tomato", category: "food", shoppable: true, english: "tomato", hebrew: "עגבנייה" }),
  Object.freeze({ id: "carrot", category: "food", shoppable: true, english: "carrot", hebrew: "גזר" }),
  Object.freeze({ id: "corn", category: "food", shoppable: true, english: "corn", hebrew: "תירס" }),
  Object.freeze({ id: "potato", category: "food", shoppable: true, english: "potato", hebrew: "תפוח אדמה" }),
  Object.freeze({ id: "mushroom", category: "food", shoppable: true, english: "mushroom", hebrew: "פטרייה" }),
  Object.freeze({ id: "bread", category: "food", shoppable: true, english: "bread", hebrew: "לחם" }),
  Object.freeze({ id: "egg", category: "food", shoppable: true, english: "egg", hebrew: "ביצה" }),
  Object.freeze({ id: "cheese", category: "food", shoppable: true, english: "cheese", hebrew: "גבינה" }),
  Object.freeze({ id: "milk", category: "food", shoppable: true, english: "milk", hebrew: "חלב" }),
  Object.freeze({ id: "water", category: "food", shoppable: true, english: "water", hebrew: "מים" }),
  Object.freeze({ id: "cake", category: "food", shoppable: true, english: "cake", hebrew: "עוגה" }),
  Object.freeze({ id: "cookie", category: "food", shoppable: true, english: "cookie", hebrew: "עוגייה" }),
  Object.freeze({ id: "ice-cream", category: "food", shoppable: true, english: "ice cream", hebrew: "גלידה" }),
  Object.freeze({ id: "pizza", category: "food", shoppable: true, english: "pizza", hebrew: "פיצה" }),
  Object.freeze({ id: "hamburger", category: "food", shoppable: true, english: "hamburger", hebrew: "המבורגר" }),
  Object.freeze({ id: "fries", category: "food", shoppable: true, english: "fries", hebrew: "צ׳יפס" }),
  Object.freeze({ id: "sandwich", category: "food", shoppable: true, english: "sandwich", hebrew: "כריך" }),
  Object.freeze({ id: "rice", category: "food", shoppable: true, english: "rice", hebrew: "אורז" }),
  Object.freeze({ id: "spaghetti", category: "food", shoppable: true, english: "spaghetti", hebrew: "ספגטי" }),
  Object.freeze({ id: "soup", category: "food", shoppable: true, english: "soup", hebrew: "מרק" }),
  Object.freeze({ id: "honey", category: "food", shoppable: true, english: "honey", hebrew: "דבש" }),
  Object.freeze({ id: "candy", category: "food", shoppable: true, english: "candy", hebrew: "סוכרייה" }),
  Object.freeze({ id: "chocolate", category: "food", shoppable: true, english: "chocolate", hebrew: "שוקולד" }),
  Object.freeze({ id: "doughnut", category: "food", shoppable: true, english: "doughnut", hebrew: "סופגנייה" }),
  Object.freeze({ id: "house", category: "home", shoppable: false, english: "house", hebrew: "בית" }),
  Object.freeze({ id: "door", category: "home", shoppable: false, english: "door", hebrew: "דלת" }),
  Object.freeze({ id: "bed", category: "home", shoppable: true, english: "bed", hebrew: "מיטה" }),
  Object.freeze({ id: "chair", category: "home", shoppable: true, english: "chair", hebrew: "כיסא" }),
  Object.freeze({ id: "couch", category: "home", shoppable: true, english: "couch", hebrew: "ספה" }),
  Object.freeze({ id: "lamp", category: "home", shoppable: true, english: "lamp", hebrew: "מנורה" }),
  Object.freeze({ id: "key", category: "home", shoppable: true, english: "key", hebrew: "מפתח" }),
  Object.freeze({ id: "clock", category: "home", shoppable: true, english: "clock", hebrew: "שעון" }),
  Object.freeze({ id: "cup", category: "home", shoppable: true, english: "cup", hebrew: "כוס" }),
  Object.freeze({ id: "plate", category: "home", shoppable: true, english: "plate", hebrew: "צלחת" }),
  Object.freeze({ id: "spoon", category: "home", shoppable: true, english: "spoon", hebrew: "כף" }),
  Object.freeze({ id: "fork", category: "home", shoppable: true, english: "fork", hebrew: "מזלג" }),
  Object.freeze({ id: "toothbrush", category: "home", shoppable: true, english: "toothbrush", hebrew: "מברשת שיניים" }),
  Object.freeze({ id: "soap", category: "home", shoppable: true, english: "soap", hebrew: "סבון" }),
  Object.freeze({ id: "scissors", category: "home", shoppable: true, english: "scissors", hebrew: "מספריים" }),
  Object.freeze({ id: "phone", category: "home", shoppable: true, english: "phone", hebrew: "טלפון" }),
  Object.freeze({ id: "umbrella", category: "home", shoppable: true, english: "umbrella", hebrew: "מטרייה" }),
  Object.freeze({ id: "radio", category: "home", shoppable: true, english: "radio", hebrew: "רדיו" }),
  Object.freeze({ id: "sun", category: "nature", shoppable: false, english: "sun", hebrew: "שמש" }),
  Object.freeze({ id: "moon", category: "nature", shoppable: false, english: "moon", hebrew: "ירח" }),
  Object.freeze({ id: "star", category: "nature", shoppable: false, english: "star", hebrew: "כוכב" }),
  Object.freeze({ id: "cloud", category: "nature", shoppable: false, english: "cloud", hebrew: "ענן" }),
  Object.freeze({ id: "rain", category: "nature", shoppable: false, english: "rain", hebrew: "גשם" }),
  Object.freeze({ id: "rainbow", category: "nature", shoppable: false, english: "rainbow", hebrew: "קשת" }),
  Object.freeze({ id: "tree", category: "nature", shoppable: false, english: "tree", hebrew: "עץ" }),
  Object.freeze({ id: "flower", category: "nature", shoppable: false, english: "flower", hebrew: "פרח" }),
  Object.freeze({ id: "leaf", category: "nature", shoppable: false, english: "leaf", hebrew: "עלה" }),
  Object.freeze({ id: "snowflake", category: "nature", shoppable: false, english: "snowflake", hebrew: "פתית שלג" }),
  Object.freeze({ id: "fire", category: "nature", shoppable: false, english: "fire", hebrew: "אש" }),
  Object.freeze({ id: "mountain", category: "nature", shoppable: false, english: "mountain", hebrew: "הר" }),
  Object.freeze({ id: "volcano", category: "nature", shoppable: false, english: "volcano", hebrew: "הר געש" }),
  Object.freeze({ id: "ocean", category: "nature", shoppable: false, english: "ocean", hebrew: "ים" }),
  Object.freeze({ id: "cactus", category: "nature", shoppable: false, english: "cactus", hebrew: "קקטוס" }),
  Object.freeze({ id: "car", category: "transport", shoppable: false, english: "car", hebrew: "מכונית" }),
  Object.freeze({ id: "bus", category: "transport", shoppable: false, english: "bus", hebrew: "אוטובוס" }),
  Object.freeze({ id: "train", category: "transport", shoppable: false, english: "train", hebrew: "רכבת" }),
  Object.freeze({ id: "airplane", category: "transport", shoppable: false, english: "airplane", hebrew: "מטוס" }),
  Object.freeze({ id: "boat", category: "transport", shoppable: false, english: "boat", hebrew: "סירה" }),
  Object.freeze({ id: "bicycle", category: "transport", shoppable: false, english: "bicycle", hebrew: "אופניים" }),
  Object.freeze({ id: "scooter", category: "transport", shoppable: false, english: "scooter", hebrew: "קורקינט" }),
  Object.freeze({ id: "tractor", category: "transport", shoppable: false, english: "tractor", hebrew: "טרקטור" }),
  Object.freeze({ id: "taxi", category: "transport", shoppable: false, english: "taxi", hebrew: "מונית" }),
  Object.freeze({ id: "rocket", category: "transport", shoppable: false, english: "rocket", hebrew: "טיל" }),
  Object.freeze({ id: "hat", category: "clothes", shoppable: true, english: "hat", hebrew: "כובע" }),
  Object.freeze({ id: "shirt", category: "clothes", shoppable: true, english: "shirt", hebrew: "חולצה" }),
  Object.freeze({ id: "dress", category: "clothes", shoppable: true, english: "dress", hebrew: "שמלה" }),
  Object.freeze({ id: "pants", category: "clothes", shoppable: true, english: "pants", hebrew: "מכנסיים" }),
  Object.freeze({ id: "shoe", category: "clothes", shoppable: true, english: "shoe", hebrew: "נעל" }),
  Object.freeze({ id: "sock", category: "clothes", shoppable: true, english: "sock", hebrew: "גרב" }),
  Object.freeze({ id: "coat", category: "clothes", shoppable: true, english: "coat", hebrew: "מעיל" }),
  Object.freeze({ id: "scarf", category: "clothes", shoppable: true, english: "scarf", hebrew: "צעיף" }),
  Object.freeze({ id: "glove", category: "clothes", shoppable: true, english: "glove", hebrew: "כפפה" }),
  Object.freeze({ id: "eye", category: "body", shoppable: false, english: "eye", hebrew: "עין" }),
  Object.freeze({ id: "ear", category: "body", shoppable: false, english: "ear", hebrew: "אוזן" }),
  Object.freeze({ id: "nose", category: "body", shoppable: false, english: "nose", hebrew: "אף" }),
  Object.freeze({ id: "mouth", category: "body", shoppable: false, english: "mouth", hebrew: "פה" }),
  Object.freeze({ id: "tooth", category: "body", shoppable: false, english: "tooth", hebrew: "שן" }),
  Object.freeze({ id: "hand", category: "body", shoppable: false, english: "hand", hebrew: "יד" }),
  Object.freeze({ id: "foot", category: "body", shoppable: false, english: "foot", hebrew: "רגל" }),
  Object.freeze({ id: "brain", category: "body", shoppable: false, english: "brain", hebrew: "מוח" }),
  Object.freeze({ id: "ball", category: "toys", shoppable: true, english: "ball", hebrew: "כדור" }),
  Object.freeze({ id: "book", category: "toys", shoppable: true, english: "book", hebrew: "ספר" }),
  Object.freeze({ id: "pencil", category: "toys", shoppable: true, english: "pencil", hebrew: "עיפרון" }),
  Object.freeze({ id: "crayon", category: "toys", shoppable: true, english: "crayon", hebrew: "צבע" }),
  Object.freeze({ id: "backpack", category: "toys", shoppable: true, english: "backpack", hebrew: "תיק" }),
  Object.freeze({ id: "balloon", category: "toys", shoppable: true, english: "balloon", hebrew: "בלון" }),
  Object.freeze({ id: "kite", category: "toys", shoppable: true, english: "kite", hebrew: "עפיפון" }),
  Object.freeze({ id: "teddy-bear", category: "toys", shoppable: true, english: "teddy bear", hebrew: "דובי" }),
  Object.freeze({ id: "baby", category: "people", shoppable: false, english: "baby", hebrew: "תינוק" }),
  Object.freeze({ id: "child", category: "people", shoppable: false, english: "child", hebrew: "ילד/ה" }),
  Object.freeze({ id: "girl", category: "people", shoppable: false, english: "girl", hebrew: "ילדה" }),
  Object.freeze({ id: "boy", category: "people", shoppable: false, english: "boy", hebrew: "ילד" }),
  Object.freeze({ id: "teacher", category: "people", shoppable: false, english: "teacher", hebrew: "מורה" }),
  Object.freeze({ id: "classroom", category: "school", shoppable: false, english: "classroom", hebrew: "כיתה" }),
  Object.freeze({ id: "desk", category: "school", shoppable: true, english: "desk", hebrew: "שולחן כתיבה" }),
  Object.freeze({ id: "notebook", category: "school", shoppable: true, english: "notebook", hebrew: "מחברת" }),
  Object.freeze({ id: "ruler", category: "school", shoppable: true, english: "ruler", hebrew: "סרגל" }),
  Object.freeze({ id: "eraser", category: "school", shoppable: true, english: "eraser", hebrew: "מחק" }),
  Object.freeze({ id: "marker", category: "school", shoppable: true, english: "marker", hebrew: "טוש" }),
  Object.freeze({ id: "glue", category: "school", shoppable: true, english: "glue", hebrew: "דבק" }),
  Object.freeze({ id: "paper", category: "school", shoppable: true, english: "paper", hebrew: "נייר" }),
  Object.freeze({ id: "computer", category: "school", shoppable: true, english: "computer", hebrew: "מחשב" }),
  Object.freeze({ id: "calculator", category: "school", shoppable: true, english: "calculator", hebrew: "מחשבון" }),
  Object.freeze({ id: "paintbrush", category: "school", shoppable: true, english: "paintbrush", hebrew: "מכחול" }),
  Object.freeze({ id: "camera", category: "school", shoppable: true, english: "camera", hebrew: "מצלמה" }),
  Object.freeze({ id: "map", category: "school", shoppable: true, english: "map", hebrew: "מפה" }),
  Object.freeze({ id: "calendar", category: "school", shoppable: true, english: "calendar", hebrew: "לוח שנה" }),
  Object.freeze({ id: "dictionary", category: "school", shoppable: true, english: "dictionary", hebrew: "מילון" }),
  Object.freeze({ id: "park", category: "places", shoppable: false, english: "park", hebrew: "פארק" }),
  Object.freeze({ id: "playground", category: "places", shoppable: false, english: "playground", hebrew: "מגרש משחקים" }),
  Object.freeze({ id: "school", category: "places", shoppable: false, english: "school", hebrew: "בית ספר" }),
  Object.freeze({ id: "library", category: "places", shoppable: false, english: "library", hebrew: "ספרייה" }),
  Object.freeze({ id: "hospital", category: "places", shoppable: false, english: "hospital", hebrew: "בית חולים" }),
  Object.freeze({ id: "supermarket", category: "places", shoppable: false, english: "supermarket", hebrew: "סופרמרקט" }),
  Object.freeze({ id: "beach", category: "places", shoppable: false, english: "beach", hebrew: "חוף" }),
  Object.freeze({ id: "zoo", category: "places", shoppable: false, english: "zoo", hebrew: "גן חיות" }),
  Object.freeze({ id: "farm", category: "places", shoppable: false, english: "farm", hebrew: "חווה" }),
  Object.freeze({ id: "cinema", category: "places", shoppable: false, english: "cinema", hebrew: "קולנוע" }),
  Object.freeze({ id: "restaurant", category: "places", shoppable: false, english: "restaurant", hebrew: "מסעדה" }),
  Object.freeze({ id: "bakery", category: "places", shoppable: false, english: "bakery", hebrew: "מאפייה" }),
  Object.freeze({ id: "station", category: "places", shoppable: false, english: "station", hebrew: "תחנה" }),
  Object.freeze({ id: "airport", category: "places", shoppable: false, english: "airport", hebrew: "נמל תעופה" }),
  Object.freeze({ id: "bridge", category: "places", shoppable: false, english: "bridge", hebrew: "גשר" }),
  Object.freeze({ id: "basketball", category: "sports", shoppable: true, english: "basketball", hebrew: "כדורסל" }),
  Object.freeze({ id: "tennis", category: "sports", shoppable: false, english: "tennis", hebrew: "טניס" }),
  Object.freeze({ id: "baseball", category: "sports", shoppable: true, english: "baseball", hebrew: "בייסבול" }),
  Object.freeze({ id: "volleyball", category: "sports", shoppable: true, english: "volleyball", hebrew: "כדורעף" }),
  Object.freeze({ id: "football", category: "sports", shoppable: true, english: "football", hebrew: "כדורגל" }),
  Object.freeze({ id: "badminton", category: "sports", shoppable: false, english: "badminton", hebrew: "בדמינטון" }),
  Object.freeze({ id: "table-tennis", category: "sports", shoppable: false, english: "table tennis", hebrew: "טניס שולחן" }),
  Object.freeze({ id: "swimming", category: "sports", shoppable: false, english: "swimming", hebrew: "שחייה" }),
  Object.freeze({ id: "running", category: "sports", shoppable: false, english: "running", hebrew: "ריצה" }),
  Object.freeze({ id: "cycling", category: "sports", shoppable: false, english: "cycling", hebrew: "רכיבה על אופניים" }),
  Object.freeze({ id: "gymnastics", category: "sports", shoppable: false, english: "gymnastics", hebrew: "התעמלות" }),
  Object.freeze({ id: "goal", category: "sports", shoppable: false, english: "goal", hebrew: "שער" }),
  Object.freeze({ id: "medal", category: "sports", shoppable: true, english: "medal", hebrew: "מדליה" }),
  Object.freeze({ id: "trophy", category: "sports", shoppable: true, english: "trophy", hebrew: "גביע" }),
  Object.freeze({ id: "skateboard", category: "sports", shoppable: true, english: "skateboard", hebrew: "סקייטבורד" }),
  Object.freeze({ id: "run", category: "actions", shoppable: false, english: "run", hebrew: "לרוץ" }),
  Object.freeze({ id: "walk", category: "actions", shoppable: false, english: "walk", hebrew: "ללכת" }),
  Object.freeze({ id: "jump", category: "actions", shoppable: false, english: "jump", hebrew: "לקפוץ" }),
  Object.freeze({ id: "swim", category: "actions", shoppable: false, english: "swim", hebrew: "לשחות" }),
  Object.freeze({ id: "dance", category: "actions", shoppable: false, english: "dance", hebrew: "לרקוד" }),
  Object.freeze({ id: "sing", category: "actions", shoppable: false, english: "sing", hebrew: "לשיר" }),
  Object.freeze({ id: "read", category: "actions", shoppable: false, english: "read", hebrew: "לקרוא" }),
  Object.freeze({ id: "write", category: "actions", shoppable: false, english: "write", hebrew: "לכתוב" }),
  Object.freeze({ id: "draw", category: "actions", shoppable: false, english: "draw", hebrew: "לצייר" }),
  Object.freeze({ id: "eat", category: "actions", shoppable: false, english: "eat", hebrew: "לאכול" }),
  Object.freeze({ id: "drink", category: "actions", shoppable: false, english: "drink", hebrew: "לשתות" }),
  Object.freeze({ id: "sleep", category: "actions", shoppable: false, english: "sleep", hebrew: "לישון" }),
  Object.freeze({ id: "laugh", category: "actions", shoppable: false, english: "laugh", hebrew: "לצחוק" }),
  Object.freeze({ id: "cry", category: "actions", shoppable: false, english: "cry", hebrew: "לבכות" }),
  Object.freeze({ id: "listen", category: "actions", shoppable: false, english: "listen", hebrew: "להקשיב" }),
  Object.freeze({ id: "red-heart", category: "colors", shoppable: true, english: "red heart", hebrew: "לב אדום" }),
  Object.freeze({ id: "blue-heart", category: "colors", shoppable: true, english: "blue heart", hebrew: "לב כחול" }),
  Object.freeze({ id: "yellow-heart", category: "colors", shoppable: true, english: "yellow heart", hebrew: "לב צהוב" }),
  Object.freeze({ id: "green-heart", category: "colors", shoppable: true, english: "green heart", hebrew: "לב ירוק" }),
  Object.freeze({ id: "purple-heart", category: "colors", shoppable: true, english: "purple heart", hebrew: "לב סגול" }),
  Object.freeze({ id: "red-book", category: "colors", shoppable: true, english: "red book", hebrew: "ספר אדום" }),
  Object.freeze({ id: "blue-book", category: "colors", shoppable: true, english: "blue book", hebrew: "ספר כחול" }),
  Object.freeze({ id: "orange-book", category: "colors", shoppable: true, english: "orange book", hebrew: "ספר כתום" }),
  Object.freeze({ id: "green-book", category: "colors", shoppable: true, english: "green book", hebrew: "ספר ירוק" }),
  Object.freeze({ id: "red-square", category: "colors", shoppable: true, english: "red square", hebrew: "ריבוע אדום" }),
  Object.freeze({ id: "blue-square", category: "colors", shoppable: true, english: "blue square", hebrew: "ריבוע כחול" }),
  Object.freeze({ id: "yellow-square", category: "colors", shoppable: true, english: "yellow square", hebrew: "ריבוע צהוב" }),
  Object.freeze({ id: "green-square", category: "colors", shoppable: true, english: "green square", hebrew: "ריבוע ירוק" }),
  Object.freeze({ id: "orange-heart", category: "colors", shoppable: true, english: "orange heart", hebrew: "לב כתום" }),
  Object.freeze({ id: "brown-circle", category: "colors", shoppable: true, english: "brown circle", hebrew: "עיגול חום" }),
  Object.freeze({ id: "white-circle", category: "colors", shoppable: true, english: "white circle", hebrew: "עיגול לבן" }),
]);
