export type WordCategory = 'animals' | 'food' | 'home' | 'clothes' | 'body' | 'nature' | 'transport' | 'toys' | 'people' | 'colors' | 'school' | 'places' | 'sports' | 'actions';

export interface VocabWord {
  id: string;
  english: string;
  hebrew: string;
  drawing: string;
  category: WordCategory;
  shoppable?: boolean;
}

export const COLOR_VOCAB_WORDS: VocabWord[] = [
  { id: 'red-heart', english: 'red heart', hebrew: 'לב אדום', drawing: '❤️', category: 'colors', shoppable: true },
  { id: 'blue-heart', english: 'blue heart', hebrew: 'לב כחול', drawing: '💙', category: 'colors', shoppable: true },
  { id: 'yellow-heart', english: 'yellow heart', hebrew: 'לב צהוב', drawing: '💛', category: 'colors', shoppable: true },
  { id: 'green-heart', english: 'green heart', hebrew: 'לב ירוק', drawing: '💚', category: 'colors', shoppable: true },
  { id: 'purple-heart', english: 'purple heart', hebrew: 'לב סגול', drawing: '💜', category: 'colors', shoppable: true },
  { id: 'red-book', english: 'red book', hebrew: 'ספר אדום', drawing: '📕', category: 'colors', shoppable: true },
  { id: 'blue-book', english: 'blue book', hebrew: 'ספר כחול', drawing: '📘', category: 'colors', shoppable: true },
  { id: 'orange-book', english: 'orange book', hebrew: 'ספר כתום', drawing: '📙', category: 'colors', shoppable: true },
  { id: 'green-book', english: 'green book', hebrew: 'ספר ירוק', drawing: '📗', category: 'colors', shoppable: true },
  { id: 'red-square', english: 'red square', hebrew: 'ריבוע אדום', drawing: '🟥', category: 'colors', shoppable: true },
  { id: 'blue-square', english: 'blue square', hebrew: 'ריבוע כחול', drawing: '🟦', category: 'colors', shoppable: true },
  { id: 'yellow-square', english: 'yellow square', hebrew: 'ריבוע צהוב', drawing: '🟨', category: 'colors', shoppable: true },
  { id: 'green-square', english: 'green square', hebrew: 'ריבוע ירוק', drawing: '🟩', category: 'colors', shoppable: true },
  { id: 'orange-heart', english: 'orange heart', hebrew: 'לב כתום', drawing: '🧡', category: 'colors', shoppable: true },
  { id: 'brown-circle', english: 'brown circle', hebrew: 'עיגול חום', drawing: '🟤', category: 'colors', shoppable: true },
  { id: 'white-circle', english: 'white circle', hebrew: 'עיגול לבן', drawing: '⚪', category: 'colors', shoppable: true },
];

export const VOCAB_WORDS: VocabWord[] = [
  { id: 'dog', english: 'dog', hebrew: 'כלב', drawing: '🐶', category: 'animals' },
  { id: 'cat', english: 'cat', hebrew: 'חתול', drawing: '🐱', category: 'animals' },
  { id: 'fish', english: 'fish', hebrew: 'דג', drawing: '🐟', category: 'animals' },
  { id: 'bird', english: 'bird', hebrew: 'ציפור', drawing: '🐦', category: 'animals' },
  { id: 'rabbit', english: 'rabbit', hebrew: 'ארנב', drawing: '🐰', category: 'animals' },
  { id: 'bear', english: 'bear', hebrew: 'דוב', drawing: '🐻', category: 'animals' },
  { id: 'fox', english: 'fox', hebrew: 'שועל', drawing: '🦊', category: 'animals' },
  { id: 'frog', english: 'frog', hebrew: 'צפרדע', drawing: '🐸', category: 'animals' },
  { id: 'panda', english: 'panda', hebrew: 'פנדה', drawing: '🐼', category: 'animals' },
  { id: 'monkey', english: 'monkey', hebrew: 'קוף', drawing: '🐵', category: 'animals' },
  { id: 'koala', english: 'koala', hebrew: 'קואלה', drawing: '🐨', category: 'animals' },
  { id: 'lion', english: 'lion', hebrew: 'אריה', drawing: '🦁', category: 'animals' },
  { id: 'tiger', english: 'tiger', hebrew: 'נמר', drawing: '🐯', category: 'animals' },
  { id: 'cow', english: 'cow', hebrew: 'פרה', drawing: '🐮', category: 'animals' },
  { id: 'pig', english: 'pig', hebrew: 'חזיר', drawing: '🐷', category: 'animals' },
  { id: 'horse', english: 'horse', hebrew: 'סוס', drawing: '🐴', category: 'animals' },
  { id: 'sheep', english: 'sheep', hebrew: 'כבשה', drawing: '🐑', category: 'animals' },
  { id: 'chicken', english: 'chicken', hebrew: 'תרנגולת', drawing: '🐔', category: 'animals' },
  { id: 'duck', english: 'duck', hebrew: 'ברווז', drawing: '🦆', category: 'animals' },
  { id: 'penguin', english: 'penguin', hebrew: 'פינגווין', drawing: '🐧', category: 'animals' },
  { id: 'elephant', english: 'elephant', hebrew: 'פיל', drawing: '🐘', category: 'animals' },
  { id: 'giraffe', english: 'giraffe', hebrew: 'ג׳ירפה', drawing: '🦒', category: 'animals' },
  { id: 'zebra', english: 'zebra', hebrew: 'זברה', drawing: '🦓', category: 'animals' },
  { id: 'turtle', english: 'turtle', hebrew: 'צב', drawing: '🐢', category: 'animals' },
  { id: 'whale', english: 'whale', hebrew: 'לווייתן', drawing: '🐳', category: 'animals' },
  { id: 'dolphin', english: 'dolphin', hebrew: 'דולפין', drawing: '🐬', category: 'animals' },
  { id: 'butterfly', english: 'butterfly', hebrew: 'פרפר', drawing: '🦋', category: 'animals' },
  { id: 'bee', english: 'bee', hebrew: 'דבורה', drawing: '🐝', category: 'animals' },
  { id: 'snail', english: 'snail', hebrew: 'חילזון', drawing: '🐌', category: 'animals' },
  { id: 'unicorn', english: 'unicorn', hebrew: 'חד־קרן', drawing: '🦄', category: 'animals' },

  { id: 'apple', english: 'apple', hebrew: 'תפוח', drawing: '🍎', category: 'food', shoppable: true },
  { id: 'banana', english: 'banana', hebrew: 'בננה', drawing: '🍌', category: 'food', shoppable: true },
  { id: 'orange', english: 'orange', hebrew: 'תפוז', drawing: '🍊', category: 'food', shoppable: true },
  { id: 'strawberry', english: 'strawberry', hebrew: 'תות', drawing: '🍓', category: 'food', shoppable: true },
  { id: 'grapes', english: 'grapes', hebrew: 'ענבים', drawing: '🍇', category: 'food', shoppable: true },
  { id: 'watermelon', english: 'watermelon', hebrew: 'אבטיח', drawing: '🍉', category: 'food', shoppable: true },
  { id: 'pear', english: 'pear', hebrew: 'אגס', drawing: '🍐', category: 'food', shoppable: true },
  { id: 'peach', english: 'peach', hebrew: 'אפרסק', drawing: '🍑', category: 'food', shoppable: true },
  { id: 'pineapple', english: 'pineapple', hebrew: 'אננס', drawing: '🍍', category: 'food', shoppable: true },
  { id: 'lemon', english: 'lemon', hebrew: 'לימון', drawing: '🍋', category: 'food', shoppable: true },
  { id: 'cherries', english: 'cherries', hebrew: 'דובדבנים', drawing: '🍒', category: 'food', shoppable: true },
  { id: 'tomato', english: 'tomato', hebrew: 'עגבנייה', drawing: '🍅', category: 'food', shoppable: true },
  { id: 'carrot', english: 'carrot', hebrew: 'גזר', drawing: '🥕', category: 'food', shoppable: true },
  { id: 'corn', english: 'corn', hebrew: 'תירס', drawing: '🌽', category: 'food', shoppable: true },
  { id: 'potato', english: 'potato', hebrew: 'תפוח אדמה', drawing: '🥔', category: 'food', shoppable: true },
  { id: 'mushroom', english: 'mushroom', hebrew: 'פטרייה', drawing: '🍄', category: 'food', shoppable: true },
  { id: 'bread', english: 'bread', hebrew: 'לחם', drawing: '🍞', category: 'food', shoppable: true },
  { id: 'egg', english: 'egg', hebrew: 'ביצה', drawing: '🥚', category: 'food', shoppable: true },
  { id: 'cheese', english: 'cheese', hebrew: 'גבינה', drawing: '🧀', category: 'food', shoppable: true },
  { id: 'milk', english: 'milk', hebrew: 'חלב', drawing: '🥛', category: 'food', shoppable: true },
  { id: 'water', english: 'water', hebrew: 'מים', drawing: '💧', category: 'food', shoppable: true },
  { id: 'cake', english: 'cake', hebrew: 'עוגה', drawing: '🍰', category: 'food', shoppable: true },
  { id: 'cookie', english: 'cookie', hebrew: 'עוגייה', drawing: '🍪', category: 'food', shoppable: true },
  { id: 'ice-cream', english: 'ice cream', hebrew: 'גלידה', drawing: '🍦', category: 'food', shoppable: true },
  { id: 'pizza', english: 'pizza', hebrew: 'פיצה', drawing: '🍕', category: 'food', shoppable: true },
  { id: 'hamburger', english: 'hamburger', hebrew: 'המבורגר', drawing: '🍔', category: 'food', shoppable: true },
  { id: 'fries', english: 'fries', hebrew: 'צ׳יפס', drawing: '🍟', category: 'food', shoppable: true },
  { id: 'sandwich', english: 'sandwich', hebrew: 'כריך', drawing: '🥪', category: 'food', shoppable: true },
  { id: 'rice', english: 'rice', hebrew: 'אורז', drawing: '🍚', category: 'food', shoppable: true },
  { id: 'spaghetti', english: 'spaghetti', hebrew: 'ספגטי', drawing: '🍝', category: 'food', shoppable: true },
  { id: 'soup', english: 'soup', hebrew: 'מרק', drawing: '🍲', category: 'food', shoppable: true },
  { id: 'honey', english: 'honey', hebrew: 'דבש', drawing: '🍯', category: 'food', shoppable: true },
  { id: 'candy', english: 'candy', hebrew: 'סוכרייה', drawing: '🍬', category: 'food', shoppable: true },
  { id: 'chocolate', english: 'chocolate', hebrew: 'שוקולד', drawing: '🍫', category: 'food', shoppable: true },
  { id: 'doughnut', english: 'doughnut', hebrew: 'סופגנייה', drawing: '🍩', category: 'food', shoppable: true },

  { id: 'house', english: 'house', hebrew: 'בית', drawing: '🏠', category: 'home' },
  { id: 'door', english: 'door', hebrew: 'דלת', drawing: '🚪', category: 'home' },
  { id: 'bed', english: 'bed', hebrew: 'מיטה', drawing: '🛏️', category: 'home', shoppable: true },
  { id: 'chair', english: 'chair', hebrew: 'כיסא', drawing: '🪑', category: 'home', shoppable: true },
  { id: 'couch', english: 'couch', hebrew: 'ספה', drawing: '🛋️', category: 'home', shoppable: true },
  { id: 'lamp', english: 'lamp', hebrew: 'מנורה', drawing: '💡', category: 'home', shoppable: true },
  { id: 'key', english: 'key', hebrew: 'מפתח', drawing: '🔑', category: 'home', shoppable: true },
  { id: 'clock', english: 'clock', hebrew: 'שעון', drawing: '🕒', category: 'home', shoppable: true },
  { id: 'cup', english: 'cup', hebrew: 'כוס', drawing: '☕', category: 'home', shoppable: true },
  { id: 'plate', english: 'plate', hebrew: 'צלחת', drawing: '🍽️', category: 'home', shoppable: true },
  { id: 'spoon', english: 'spoon', hebrew: 'כף', drawing: '🥄', category: 'home', shoppable: true },
  { id: 'fork', english: 'fork', hebrew: 'מזלג', drawing: '🍴', category: 'home', shoppable: true },
  { id: 'toothbrush', english: 'toothbrush', hebrew: 'מברשת שיניים', drawing: '🪥', category: 'home', shoppable: true },
  { id: 'soap', english: 'soap', hebrew: 'סבון', drawing: '🧼', category: 'home', shoppable: true },
  { id: 'scissors', english: 'scissors', hebrew: 'מספריים', drawing: '✂️', category: 'home', shoppable: true },
  { id: 'phone', english: 'phone', hebrew: 'טלפון', drawing: '📱', category: 'home', shoppable: true },
  { id: 'umbrella', english: 'umbrella', hebrew: 'מטרייה', drawing: '☂️', category: 'home', shoppable: true },
  { id: 'radio', english: 'radio', hebrew: 'רדיו', drawing: '📻', category: 'home', shoppable: true },

  { id: 'sun', english: 'sun', hebrew: 'שמש', drawing: '☀️', category: 'nature' },
  { id: 'moon', english: 'moon', hebrew: 'ירח', drawing: '🌙', category: 'nature' },
  { id: 'star', english: 'star', hebrew: 'כוכב', drawing: '⭐', category: 'nature' },
  { id: 'cloud', english: 'cloud', hebrew: 'ענן', drawing: '☁️', category: 'nature' },
  { id: 'rain', english: 'rain', hebrew: 'גשם', drawing: '🌧️', category: 'nature' },
  { id: 'rainbow', english: 'rainbow', hebrew: 'קשת', drawing: '🌈', category: 'nature' },
  { id: 'tree', english: 'tree', hebrew: 'עץ', drawing: '🌳', category: 'nature' },
  { id: 'flower', english: 'flower', hebrew: 'פרח', drawing: '🌸', category: 'nature' },
  { id: 'leaf', english: 'leaf', hebrew: 'עלה', drawing: '🍃', category: 'nature' },
  { id: 'snowflake', english: 'snowflake', hebrew: 'פתית שלג', drawing: '❄️', category: 'nature' },
  { id: 'fire', english: 'fire', hebrew: 'אש', drawing: '🔥', category: 'nature' },
  { id: 'mountain', english: 'mountain', hebrew: 'הר', drawing: '🏔️', category: 'nature' },
  { id: 'volcano', english: 'volcano', hebrew: 'הר געש', drawing: '🌋', category: 'nature' },
  { id: 'ocean', english: 'ocean', hebrew: 'ים', drawing: '🌊', category: 'nature' },
  { id: 'cactus', english: 'cactus', hebrew: 'קקטוס', drawing: '🌵', category: 'nature' },

  { id: 'car', english: 'car', hebrew: 'מכונית', drawing: '🚗', category: 'transport' },
  { id: 'bus', english: 'bus', hebrew: 'אוטובוס', drawing: '🚌', category: 'transport' },
  { id: 'train', english: 'train', hebrew: 'רכבת', drawing: '🚆', category: 'transport' },
  { id: 'airplane', english: 'airplane', hebrew: 'מטוס', drawing: '✈️', category: 'transport' },
  { id: 'boat', english: 'boat', hebrew: 'סירה', drawing: '⛵', category: 'transport' },
  { id: 'bicycle', english: 'bicycle', hebrew: 'אופניים', drawing: '🚲', category: 'transport' },
  { id: 'scooter', english: 'scooter', hebrew: 'קורקינט', drawing: '🛴', category: 'transport' },
  { id: 'tractor', english: 'tractor', hebrew: 'טרקטור', drawing: '🚜', category: 'transport' },
  { id: 'taxi', english: 'taxi', hebrew: 'מונית', drawing: '🚕', category: 'transport' },
  { id: 'rocket', english: 'rocket', hebrew: 'טיל', drawing: '🚀', category: 'transport' },

  { id: 'hat', english: 'hat', hebrew: 'כובע', drawing: '👒', category: 'clothes', shoppable: true },
  { id: 'shirt', english: 'shirt', hebrew: 'חולצה', drawing: '👕', category: 'clothes', shoppable: true },
  { id: 'dress', english: 'dress', hebrew: 'שמלה', drawing: '👗', category: 'clothes', shoppable: true },
  { id: 'pants', english: 'pants', hebrew: 'מכנסיים', drawing: '👖', category: 'clothes', shoppable: true },
  { id: 'shoe', english: 'shoe', hebrew: 'נעל', drawing: '👟', category: 'clothes', shoppable: true },
  { id: 'sock', english: 'sock', hebrew: 'גרב', drawing: '🧦', category: 'clothes', shoppable: true },
  { id: 'coat', english: 'coat', hebrew: 'מעיל', drawing: '🧥', category: 'clothes', shoppable: true },
  { id: 'scarf', english: 'scarf', hebrew: 'צעיף', drawing: '🧣', category: 'clothes', shoppable: true },
  { id: 'glove', english: 'glove', hebrew: 'כפפה', drawing: '🧤', category: 'clothes', shoppable: true },

  { id: 'eye', english: 'eye', hebrew: 'עין', drawing: '👁️', category: 'body' },
  { id: 'ear', english: 'ear', hebrew: 'אוזן', drawing: '👂', category: 'body' },
  { id: 'nose', english: 'nose', hebrew: 'אף', drawing: '👃', category: 'body' },
  { id: 'mouth', english: 'mouth', hebrew: 'פה', drawing: '👄', category: 'body' },
  { id: 'tooth', english: 'tooth', hebrew: 'שן', drawing: '🦷', category: 'body' },
  { id: 'hand', english: 'hand', hebrew: 'יד', drawing: '✋', category: 'body' },
  { id: 'foot', english: 'foot', hebrew: 'רגל', drawing: '🦶', category: 'body' },
  { id: 'brain', english: 'brain', hebrew: 'מוח', drawing: '🧠', category: 'body' },

  { id: 'ball', english: 'ball', hebrew: 'כדור', drawing: '⚽', category: 'toys', shoppable: true },
  { id: 'book', english: 'book', hebrew: 'ספר', drawing: '📖', category: 'toys', shoppable: true },
  { id: 'pencil', english: 'pencil', hebrew: 'עיפרון', drawing: '✏️', category: 'toys', shoppable: true },
  { id: 'crayon', english: 'crayon', hebrew: 'צבע', drawing: '🖍️', category: 'toys', shoppable: true },
  { id: 'backpack', english: 'backpack', hebrew: 'תיק', drawing: '🎒', category: 'toys', shoppable: true },
  { id: 'balloon', english: 'balloon', hebrew: 'בלון', drawing: '🎈', category: 'toys', shoppable: true },
  { id: 'kite', english: 'kite', hebrew: 'עפיפון', drawing: '🪁', category: 'toys', shoppable: true },
  { id: 'teddy-bear', english: 'teddy bear', hebrew: 'דובי', drawing: '🧸', category: 'toys', shoppable: true },

  { id: 'baby', english: 'baby', hebrew: 'תינוק', drawing: '👶', category: 'people' },
  { id: 'child', english: 'child', hebrew: 'ילד/ה', drawing: '🧒', category: 'people' },
  { id: 'girl', english: 'girl', hebrew: 'ילדה', drawing: '👧', category: 'people' },
  { id: 'boy', english: 'boy', hebrew: 'ילד', drawing: '👦', category: 'people' },
  { id: 'teacher', english: 'teacher', hebrew: 'מורה', drawing: '🧑‍🏫', category: 'people' },

  { id: 'classroom', english: 'classroom', hebrew: 'כיתה', drawing: '🏫', category: 'school' },
  { id: 'desk', english: 'desk', hebrew: 'שולחן כתיבה', drawing: '🪑✏️', category: 'school', shoppable: true },
  { id: 'notebook', english: 'notebook', hebrew: 'מחברת', drawing: '📓', category: 'school', shoppable: true },
  { id: 'ruler', english: 'ruler', hebrew: 'סרגל', drawing: '📏', category: 'school', shoppable: true },
  { id: 'eraser', english: 'eraser', hebrew: 'מחק', drawing: '🧽', category: 'school', shoppable: true },
  { id: 'marker', english: 'marker', hebrew: 'טוש', drawing: '🖊️', category: 'school', shoppable: true },
  { id: 'glue', english: 'glue', hebrew: 'דבק', drawing: '🧴', category: 'school', shoppable: true },
  { id: 'paper', english: 'paper', hebrew: 'נייר', drawing: '📄', category: 'school', shoppable: true },
  { id: 'computer', english: 'computer', hebrew: 'מחשב', drawing: '💻', category: 'school', shoppable: true },
  { id: 'calculator', english: 'calculator', hebrew: 'מחשבון', drawing: '🧮', category: 'school', shoppable: true },
  { id: 'paintbrush', english: 'paintbrush', hebrew: 'מכחול', drawing: '🖌️', category: 'school', shoppable: true },
  { id: 'camera', english: 'camera', hebrew: 'מצלמה', drawing: '📷', category: 'school', shoppable: true },
  { id: 'map', english: 'map', hebrew: 'מפה', drawing: '🗺️', category: 'school', shoppable: true },
  { id: 'calendar', english: 'calendar', hebrew: 'לוח שנה', drawing: '📅', category: 'school', shoppable: true },
  { id: 'dictionary', english: 'dictionary', hebrew: 'מילון', drawing: '📕', category: 'school', shoppable: true },

  { id: 'park', english: 'park', hebrew: 'פארק', drawing: '🏞️', category: 'places' },
  { id: 'playground', english: 'playground', hebrew: 'מגרש משחקים', drawing: '🛝', category: 'places' },
  { id: 'school', english: 'school', hebrew: 'בית ספר', drawing: '🏫', category: 'places' },
  { id: 'library', english: 'library', hebrew: 'ספרייה', drawing: '📚', category: 'places' },
  { id: 'hospital', english: 'hospital', hebrew: 'בית חולים', drawing: '🏥', category: 'places' },
  { id: 'supermarket', english: 'supermarket', hebrew: 'סופרמרקט', drawing: '🛒', category: 'places' },
  { id: 'beach', english: 'beach', hebrew: 'חוף', drawing: '🏖️', category: 'places' },
  { id: 'zoo', english: 'zoo', hebrew: 'גן חיות', drawing: '🦁', category: 'places' },
  { id: 'farm', english: 'farm', hebrew: 'חווה', drawing: '🚜', category: 'places' },
  { id: 'cinema', english: 'cinema', hebrew: 'קולנוע', drawing: '🎬', category: 'places' },
  { id: 'restaurant', english: 'restaurant', hebrew: 'מסעדה', drawing: '🍽️', category: 'places' },
  { id: 'bakery', english: 'bakery', hebrew: 'מאפייה', drawing: '🥖', category: 'places' },
  { id: 'station', english: 'station', hebrew: 'תחנה', drawing: '🚉', category: 'places' },
  { id: 'airport', english: 'airport', hebrew: 'נמל תעופה', drawing: '🛫', category: 'places' },
  { id: 'bridge', english: 'bridge', hebrew: 'גשר', drawing: '🌉', category: 'places' },

  { id: 'basketball', english: 'basketball', hebrew: 'כדורסל', drawing: '🏀', category: 'sports', shoppable: true },
  { id: 'tennis', english: 'tennis', hebrew: 'טניס', drawing: '🎾', category: 'sports' },
  { id: 'baseball', english: 'baseball', hebrew: 'בייסבול', drawing: '⚾', category: 'sports', shoppable: true },
  { id: 'volleyball', english: 'volleyball', hebrew: 'כדורעף', drawing: '🏐', category: 'sports', shoppable: true },
  { id: 'football', english: 'football', hebrew: 'כדורגל', drawing: '⚽', category: 'sports', shoppable: true },
  { id: 'badminton', english: 'badminton', hebrew: 'בדמינטון', drawing: '🏸', category: 'sports' },
  { id: 'table-tennis', english: 'table tennis', hebrew: 'טניס שולחן', drawing: '🏓', category: 'sports' },
  { id: 'swimming', english: 'swimming', hebrew: 'שחייה', drawing: '🏊', category: 'sports' },
  { id: 'running', english: 'running', hebrew: 'ריצה', drawing: '🏃', category: 'sports' },
  { id: 'cycling', english: 'cycling', hebrew: 'רכיבה על אופניים', drawing: '🚴', category: 'sports' },
  { id: 'gymnastics', english: 'gymnastics', hebrew: 'התעמלות', drawing: '🤸', category: 'sports' },
  { id: 'goal', english: 'goal', hebrew: 'שער', drawing: '🥅', category: 'sports' },
  { id: 'medal', english: 'medal', hebrew: 'מדליה', drawing: '🏅', category: 'sports', shoppable: true },
  { id: 'trophy', english: 'trophy', hebrew: 'גביע', drawing: '🏆', category: 'sports', shoppable: true },
  { id: 'skateboard', english: 'skateboard', hebrew: 'סקייטבורד', drawing: '🛹', category: 'sports', shoppable: true },

  { id: 'run', english: 'run', hebrew: 'לרוץ', drawing: '🏃', category: 'actions' },
  { id: 'walk', english: 'walk', hebrew: 'ללכת', drawing: '🚶', category: 'actions' },
  { id: 'jump', english: 'jump', hebrew: 'לקפוץ', drawing: '🤸', category: 'actions' },
  { id: 'swim', english: 'swim', hebrew: 'לשחות', drawing: '🏊', category: 'actions' },
  { id: 'dance', english: 'dance', hebrew: 'לרקוד', drawing: '💃', category: 'actions' },
  { id: 'sing', english: 'sing', hebrew: 'לשיר', drawing: '🎤', category: 'actions' },
  { id: 'read', english: 'read', hebrew: 'לקרוא', drawing: '📖', category: 'actions' },
  { id: 'write', english: 'write', hebrew: 'לכתוב', drawing: '✍️', category: 'actions' },
  { id: 'draw', english: 'draw', hebrew: 'לצייר', drawing: '🎨', category: 'actions' },
  { id: 'eat', english: 'eat', hebrew: 'לאכול', drawing: '🍽️', category: 'actions' },
  { id: 'drink', english: 'drink', hebrew: 'לשתות', drawing: '🥤', category: 'actions' },
  { id: 'sleep', english: 'sleep', hebrew: 'לישון', drawing: '😴', category: 'actions' },
  { id: 'laugh', english: 'laugh', hebrew: 'לצחוק', drawing: '😄', category: 'actions' },
  { id: 'cry', english: 'cry', hebrew: 'לבכות', drawing: '😢', category: 'actions' },
  { id: 'listen', english: 'listen', hebrew: 'להקשיב', drawing: '👂', category: 'actions' },

  ...COLOR_VOCAB_WORDS,
];
